EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EXAMEN3_CRUD_ESTUDIANTE.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Estudiante> Estudiante { get; set; }

    }
}

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Models/ErrorViewModel.cs
using System;

namespace EXAMEN3_CRUD_ESTUDIANTE.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Models/Estudiante.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EXAMEN3_CRUD_ESTUDIANTE.Models
{
    public class Estudiante
    {
        [Key]
        [Display(Name = "ID Estudiante")]
        public int Estudianteid { get; set; }

        [Required(ErrorMessage = "Se requeire el nombre del estudiante")]
        [Display(Name = "Nombre Estudiante")]
        public string Nombreestudiante { get; set; }

        [Required(ErrorMessage = "Se requeire el apellido del estudiante")]
        [Display(Name = "Apellido Estudiante")]
        public string Apellidoestudiante { get; set; }

        [Required(ErrorMessage = "Se requeire la edad del estudiante")]
        [Range(18,25)]
        [Display(Name = "Edad Estudiante")]
        public int Edadestudiante { get; set; }

        [Required(ErrorMessage = "Se requeire el correo del estudiante")]
        [EmailAddress(ErrorMessage = "El formato de correo ingresado no es valido")]
        [Display(Name = "Correo Estudiante")]
        public string Correoestudiante { get; set; }
    }
}

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EXAMEN3_CRUD_ESTUDIANTE.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EXAMEN3_CRUD_ESTUDIANTE.Controllers
{
    public class EstudianteController : Controller
    {

        private readonly ApplicationDbContext _db;

        public EstudianteController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var mostrarDatos = _db.Estudiante.ToList();
            return View(mostrarDatos);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Estudiante nuevoEstudiante)
        {
            if(ModelState.IsValid)
            {
                _db.Add(nuevoEstudiante);
                await _db.SaveChangesAsync();
                return Redirect("Index");
            }
            return View(nuevoEstudiante);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var detalleEstudiante = await _db.Estudiante.FindAsync(id);
            return View(detalleEstudiante);
        }

        public async Task<IActionResult> Edit (int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var detalleEstudiante = await _db.Estudiante.FindAsync(id);
            return View(detalleEstudiante);
        }

        [HttpPost]
        public async Task<IActionResult> Edit (Estudiante estudianteEditado)
        {
            if (ModelState.IsValid)
            {
                _db.Update(estudianteEditado);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(estudianteEditado);
        }

        public async Task<IActionResult> Delete (int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var detalleEstudiante = await _db.Estudiante.FindAsync(id);
            return View(detalleEstudiante);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var detalleEstudiante = await _db.Estudiante.FindAsync(id);
            _db.Estudiante.Remove(detalleEstudiante);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Views/Estudiante/Create.cshtml
@model EXAMEN3_CRUD_ESTUDIANTE.Models.Estudiante

@{
    ViewData["Title"] = "Create";
}

<h1>Añadir estudiante</h1>

<h4>Estudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombreestudiante" class="control-label"></label>
                <input asp-for="Nombreestudiante" class="form-control" />
                <span asp-validation-for="Nombreestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidoestudiante" class="control-label"></label>
                <input asp-for="Apellidoestudiante" class="form-control" />
                <span asp-validation-for="Apellidoestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edadestudiante" class="control-label"></label>
                <input asp-for="Edadestudiante" class="form-control" />
                <span asp-validation-for="Edadestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correoestudiante" class="control-label"></label>
                <input asp-for="Correoestudiante" class="form-control" />
                <span asp-validation-for="Correoestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la pagina principal</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Views/Estudiante/Delete.cshtml
@model EXAMEN3_CRUD_ESTUDIANTE.Models.Estudiante

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar estudiante</h1>

<h3>Neta si lo vas a borrar?</h3>
<div>
    <h4>Estudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estudianteid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estudianteid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombreestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombreestudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidoestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidoestudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edadestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edadestudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correoestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correoestudiante)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Pagina principal</a>
    </form>
</div>

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Views/Estudiante/Detail.cshtml
@model EXAMEN3_CRUD_ESTUDIANTE.Models.Estudiante

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalle del estudiante</h1>

<div>
    <h4>Estudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estudianteid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estudianteid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombreestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombreestudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidoestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidoestudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edadestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edadestudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correoestudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correoestudiante)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Estudianteid }) |
    <a asp-action="Index">Regresar a la lista</a>
</div>

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Views/Estudiante/Edit.cshtml
@model EXAMEN3_CRUD_ESTUDIANTE.Models.Estudiante

@{
    ViewData["Title"] = "Edit";
}

<h1>Modificar estudiante</h1>

<h4>Estudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Estudianteid" class="control-label"></label>
                <input asp-for="Estudianteid" class="form-control" />
                <span asp-validation-for="Estudianteid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombreestudiante" class="control-label"></label>
                <input asp-for="Nombreestudiante" class="form-control" />
                <span asp-validation-for="Nombreestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidoestudiante" class="control-label"></label>
                <input asp-for="Apellidoestudiante" class="form-control" />
                <span asp-validation-for="Apellidoestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edadestudiante" class="control-label"></label>
                <input asp-for="Edadestudiante" class="form-control" />
                <span asp-validation-for="Edadestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correoestudiante" class="control-label"></label>
                <input asp-for="Correoestudiante" class="form-control" />
                <span asp-validation-for="Correoestudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Views/Estudiante/Index.cshtml
@model IEnumerable<EXAMEN3_CRUD_ESTUDIANTE.Models.Estudiante>

@{
    ViewData["Title"] = "Index";
}

<h1>Pagina principal</h1>

<p>
    <a asp-action="Create">Añadir estudiante</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Estudianteid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombreestudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidoestudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edadestudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correoestudiante)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Estudianteid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombreestudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidoestudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edadestudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correoestudiante)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Estudianteid }) |
                @Html.ActionLink("Detail", "Detail", new { id = item.Estudianteid }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Estudianteid })
            </td>
        </tr>
}
    </tbody>
</table>

EXAMEN3_CRUD_ESTUDIANTE/EXAMEN3_CRUD_ESTUDIANTE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EXAMEN3_CRUD_ESTUDIANTE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Estudiante" asp-action="Index">EXAMEN3_CRUD_ESTUDIANTE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EXAMEN3_CRUD_ESTUDIANTE - <a asp-area="" asp-controller="Estudiante" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>